### ISSUE TITLE
P15

### ISSUE THREAD

**Issue by parnoldx** [foriequal0/tpmiddle-rs#7]
Hi, I just got a P15 and want to get the middle click working. The normal tpmiddle-0.6 seems not to work and start with errors. When I start your version it gives no error but the middle click is not working. Anything I can do to make this work?

**Comment by foriequal0** [comment]
Hi. This program is specifically targeted to my ThinkPad TrackPoint Keyboard II, so it might not work for your P15 for now.

I think you're referring [this tpmiddle](https://sdx1.net/tools/tpmiddle/).
It uses Synaptics SDK. I don't know it well and it doesn't seems to be ported to Rust.
However, if P15's TrackPoint has a HID interface that I use, I think I can manage to make it work with that.
Here's a program that scans and tests Lenovo HID devices: https://github.com/foriequal0/tpmiddle-rs/pull/6. Could you send me a `report.log`?

**Comment by parnoldx** [comment]
Hi, thanks for looking at this.
The report gives a error before I can click or press anything.
`PS C:\Users\peter\Downloads> .\report.exe

Gathering device infos.
Click the middle button once then press RETURN:
Error: LastError: 57
PS C:\Users\peter\Downloads> .\report.exe --probe
Gathering device infos.
Trying to initialize with known protocols:
Click the middle button once then press RETURN:
Error: LastError: 57
PS C:\Users\peter\Downloads>`

**Comment by foriequal0** [comment]
@parnold-x I've rebuilt the binary to include backtraces. Would you retry it with the new binary and send me the backtrace?
To get it, `$Env:RUST_BACKTRACE = "1"` in powershell. Then try `.\report.exe` again. Also it would be helpful if you let me know your OS version.
Although it dies after the error, `report.log` might contains your device configurations. Please post it here or send it to my email (you can find it on my profile page) if you don't want to post it publicly.
Thank you :)

**Comment by parnoldx** [comment]
@foriequal0 Thank you!
I tried it with the new report.exe again. Now it does not crash. But it does not react on middle click at all. 

In the log below I pressed one time the left and one time the right button and it reacts but not on the middle button. Also if i move the cursor it spams a lot of messages, so I did not move it. The report.log file contains nothing.
`
PS C:\Users\peter\Downloads> .\report.exe
Gathering device infos.
We'll capture raw input messages from all devices.
Please try not to touch other devices except TrackPoint.
Click the middle button once then press RETURN:
 - Report { path: "\\\\?\\ACPI#LEN2066#4&30398612&0#{378de44c-56ef-11d1-bc8c-00a0c91405dd}\u{0}", device_info: Mouse, raw_input: RawInput::Mouse { usFlags: 0000000000000000, usButtonFlags: 0000000000000001, usButtonData: 0000, lLastX: 0, lLastY: 0, ulExtraInformation: 0 } }
 - Report { path: "\\\\?\\ACPI#LEN2066#4&30398612&0#{378de44c-56ef-11d1-bc8c-00a0c91405dd}\u{0}", device_info: Mouse, raw_input: RawInput::Mouse { usFlags: 0000000000000000, usButtonFlags: 0000000000000010, usButtonData: 0000, lLastX: 0, lLastY: 0, ulExtraInformation: 0 } }
 - Report { path: "\\\\?\\ACPI#LEN2066#4&30398612&0#{378de44c-56ef-11d1-bc8c-00a0c91405dd}\u{0}", device_info: Mouse, raw_input: RawInput::Mouse { usFlags: 0000000000000000, usButtonFlags: 0000000000000100, usButtonData: 0000, lLastX: 0, lLastY: 0, ulExtraInformation: 0 } }
 - Report { path: "\\\\?\\ACPI#LEN2066#4&30398612&0#{378de44c-56ef-11d1-bc8c-00a0c91405dd}\u{0}", device_info: Mouse, raw_input: RawInput::Mouse { usFlags: 0000000000000000, usButtonFlags: 0000000000001000, usButtonData: 0000, lLastX: 0, lLastY: 0, ulExtraInformation: 0 } }
PS C:\Users\peter\Downloads>`

**Comment by foriequal0** [comment]
Thank you for your help!
I think it looks like a PS/2 device. I'm really sorry to say that it is hard to support your device for now.

**Comment by parnoldx** [comment]
Ok, will look futher through the internet, I need middle click (and scrolling of course) :)  Thanks again for looking at this.
